version: '3.7'

services:
  ydb-local:
    container_name: ydb-local
    hostname: localhost
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    platform: linux/amd64
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"
    volumes:
      - ydb_certs:/ydb_certs
      - ydb_data:/ydb_data
    environment:
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
      - YDB_USE_IN_MEMORY_PDISKS=true
    restart: always

volumes:
  ydb_certs:
  ydb_data:
