name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: 'b1gac1g0nm3qptu01u57'
          function-name: 'domovoy'
          service-account: 'ajeocdkp9qbbb04irg6k'
          runtime: 'python312'
          memory: '128Mb'
          entrypoint: 'index.handler'
          secrets: |
            YDB_DATABASE=e6q06hs6gktrap1i2a2c/e6qjrs8h4vpbdla7tfbl/YDB_DATABASE
            YDB_ENDPOINT=e6q06hs6gktrap1i2a2c/e6qjrs8h4vpbdla7tfbl/YDB_ENDPOINT
            YDB_HAS_CREDENTIALS=e6q06hs6gktrap1i2a2c/e6qir344lletct3sng44/YDB_HAS_CREDENTIALS
          include: |
            .
          exclude: |
            .github/**/*
            .git/**/*
            .git
            .github